### ISSUE TITLE
What's the username and password for the webgui?

### ISSUE THREAD

**Issue by Deanosim** [timstephens24/channelsdvr-docker#1]
I have a fresh install on unraid and it's asking for a username and password, I've looked though the template, dockerfile, support forum, google, and I can't find anything about it needing one.
![image](https://user-images.githubusercontent.com/4834976/187975303-9c225764-32ea-4197-a26d-8e1d26d67eeb.png)

**Comment by timstephens24** [comment]
There's nothing in my docker that would be causing this. Can you should me your docker run line that shows up after you create the container or edit the container?

**Comment by Deanosim** [comment]
Sorry completely my fault, turns out that because the container template was using host networking and another container was using bridge with the same port on the host, just had to give the container a different IP address instead of using host networking.
