### ISSUE TITLE
Does this support Raspberry Pi hardware-based transcoding

### ISSUE THREAD

**Issue by thequackdaddy** [timstephens24/channelsdvr-docker#4]
Would this be able to enable hardware encoding on a raspberry pi? If so, how? The base docker image seems to be software-only for Pi unless I'm missing thing.

**Comment by timstephens24** [comment]
It doesn't support Raspberry Pi architecture at all, sorry, only amd64.

**Comment by thequackdaddy** [comment]
That's too bad. Thanks, though!

**Comment by timstephens24** [comment]
Channels has an official one that works with Raspberry Pi. Look up fancybits/channels-dvr:tve. It should also support hardware transcoding.
